name: microservice-template
version: v2
exposure: true
environment: dev
kmskey:
loggroupname: microservice-template

container:
  containerport: 3000
  cpu: 20
  memoryreservation: 128
  memory: 256

  environment:
  - name: API_KEY
    value: a0000key
  - name: ENVIRONMENT
    value: DEV

  image: ecr-somthing-20393902/microservice-template:latest

  sidecar: false

  dockerlabels:
    version: "1.0.0"
    region: "eu-central-1"
    service: "microservice-template"
    environment: "dev"

  logstreamprefix: template-

deployment:
  context: /v1/template
  cloudfront: false
  count: 1